# Generated by Django 6.0.6 on 2026-06-23 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiops', '0021_remove_aiopsknowledgeenvironment_posture_environments'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIOpsAgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Agent 名称')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='Agent 标识')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='描述')),
                ('system_prompt', models.TextField(blank=True, default='', verbose_name='系统提示词')),
                ('welcome_message', models.CharField(blank=True, default='', max_length=255, verbose_name='欢迎语')),
                ('suggested_questions', models.JSONField(blank=True, default=list, verbose_name='建议问题')),
                ('enabled_mcp_server_ids', models.JSONField(blank=True, default=list, verbose_name='启用的 MCP')),
                ('enabled_skill_ids', models.JSONField(blank=True, default=list, verbose_name='启用的 Skill')),
                ('tool_policy', models.JSONField(blank=True, default=dict, verbose_name='工具策略')),
                ('execution_policy', models.CharField(choices=[('read_only', '只读'), ('manual_confirm', '逐操作确认'), ('full_auto', 'Full Auto')], default='manual_confirm', max_length=32, verbose_name='执行策略')),
                ('allowed_role_codes', models.JSONField(blank=True, default=list, verbose_name='允许角色')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认 Agent')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='内置')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_by', models.CharField(blank=True, default='', max_length=64, verbose_name='创建人')),
                ('updated_by', models.CharField(blank=True, default='', max_length=64, verbose_name='更新人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('default_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_profiles', to='aiops.aiopsmodelprovider', verbose_name='默认模型提供商')),
            ],
            options={
                'verbose_name': 'AIOps Agent',
                'verbose_name_plural': 'AIOps Agent',
                'ordering': ['-is_default', 'name', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='aiops_agent_profile_single_default')],
            },
        ),
    ]
