# Generated by Codex on 2026-06-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiops', '0022_aiopsagentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiopspendingaction',
            name='action_type',
            field=models.CharField(
                choices=[
                    ('execute_host_task', '执行主机任务'),
                    ('create_aiops_skill', '创建 AIOps Skill'),
                ],
                max_length=32,
                verbose_name='动作类型',
            ),
        ),
    ]
