# Generated by Django 6.0.6 on 2026-06-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiops', '0023_pending_action_create_aiops_skill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiopspendingaction',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'AIOps 执行审批', 'verbose_name_plural': 'AIOps 执行审批'},
        ),
        migrations.AlterField(
            model_name='aiopsexternaltask',
            name='action_code',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='运行策略'),
        ),
        migrations.AlterField(
            model_name='aiopspendingaction',
            name='action_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='事项参数'),
        ),
        migrations.AlterField(
            model_name='aiopspendingaction',
            name='action_type',
            field=models.CharField(choices=[('execute_host_task', '执行主机任务'), ('create_aiops_skill', '创建 AIOps Skill')], max_length=32, verbose_name='事项类型'),
        ),
        migrations.AlterField(
            model_name='aiopspendingaction',
            name='title',
            field=models.CharField(default='', max_length=128, verbose_name='事项标题'),
        ),
        migrations.AlterField(
            model_name='aiopsskill',
            name='applicable_actions',
            field=models.JSONField(blank=True, default=list, verbose_name='推荐场景'),
        ),
    ]
