# Generated by Django 6.0.6 on 2026-06-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiops', '0024_alter_aiopspendingaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiopschatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', '文本'), ('analysis', '分析'), ('action', '执行事项'), ('error', '错误')], default='text', max_length=16, verbose_name='消息类型'),
        ),
    ]
