# Generated by Django 6.0.6 on 2026-06-29 08:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiops', '0026_agent_environment_scope'),
        ('ops', '0057_delete_system_posture_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIOpsIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Incident 标题')),
                ('status', models.CharField(choices=[('open', '新建'), ('investigating', '调查中'), ('mitigating', '处置中'), ('verifying', '验证中'), ('resolved', '已恢复'), ('closed', '已关闭')], default='open', max_length=24, verbose_name='状态')),
                ('severity', models.CharField(choices=[('critical', '严重'), ('warning', '警告'), ('info', '信息')], default='info', max_length=16, verbose_name='严重级别')),
                ('source_type', models.CharField(choices=[('alert', '告警'), ('manual', '手动')], default='alert', max_length=24, verbose_name='来源类型')),
                ('dedupe_key', models.CharField(db_index=True, max_length=320, verbose_name='归并键')),
                ('environment', models.CharField(blank=True, default='', max_length=64, verbose_name='环境')),
                ('cluster', models.CharField(blank=True, default='', max_length=128, verbose_name='集群')),
                ('namespace', models.CharField(blank=True, default='', max_length=128, verbose_name='命名空间')),
                ('service', models.CharField(blank=True, default='', max_length=128, verbose_name='服务')),
                ('resource_type', models.CharField(blank=True, default='', max_length=64, verbose_name='资源类型')),
                ('resource', models.CharField(blank=True, default='', max_length=256, verbose_name='资源标识')),
                ('impact_summary', models.TextField(blank=True, default='', verbose_name='影响摘要')),
                ('owner', models.CharField(blank=True, default='', max_length=64, verbose_name='负责人')),
                ('alert_count', models.PositiveIntegerField(default=0, verbose_name='关联告警数')),
                ('active_alert_count', models.PositiveIntegerField(default=0, verbose_name='活跃告警数')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='首次触发时间')),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='平台检测时间')),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最近告警时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='恢复时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AIOps Incident',
                'verbose_name_plural': 'AIOps Incident',
                'ordering': ['-last_seen_at', '-id'],
                'indexes': [models.Index(fields=['status', 'severity'], name='aiops_aiops_status_cadb7c_idx'), models.Index(fields=['environment', 'service'], name='aiops_aiops_environ_44b147_idx'), models.Index(fields=['cluster', 'namespace'], name='aiops_aiops_cluster_25e752_idx'), models.Index(fields=['started_at'], name='aiops_aiops_started_62011b_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIOpsIncidentAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('primary', '主告警'), ('related', '相关告警'), ('symptom', '症状告警'), ('resolved_signal', '恢复信号')], default='related', max_length=24, verbose_name='关联角色')),
                ('linked_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='关联原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_links', to='ops.alert', verbose_name='告警')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_links', to='aiops.aiopsincident', verbose_name='Incident')),
            ],
            options={
                'verbose_name': 'AIOps Incident 告警关联',
                'verbose_name_plural': 'AIOps Incident 告警关联',
                'ordering': ['incident_id', 'id'],
                'indexes': [models.Index(fields=['alert'], name='aiops_aiops_alert_i_2a32cf_idx'), models.Index(fields=['incident', 'role'], name='aiops_aiops_inciden_21a8f5_idx')],
                'constraints': [models.UniqueConstraint(fields=('incident', 'alert'), name='aiops_incident_alert_unique')],
            },
        ),
    ]
