# Generated by Django 6.0.6 on 2026-06-29 09:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiops', '0027_aiopsincident_aiopsincidentalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIOpsIncidentEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('alert', '告警证据'), ('metric', '指标证据'), ('log', '日志证据'), ('trace', '链路证据'), ('k8s', 'K8s 证据'), ('change', '变更证据'), ('event', '事件证据'), ('task', '任务证据'), ('topology', '拓扑证据')], max_length=24, verbose_name='证据类型')),
                ('source', models.CharField(max_length=96, verbose_name='来源')),
                ('scope', models.JSONField(blank=True, default=dict, verbose_name='取证范围')),
                ('window_start', models.DateTimeField(blank=True, null=True, verbose_name='窗口开始')),
                ('window_end', models.DateTimeField(blank=True, null=True, verbose_name='窗口结束')),
                ('summary', models.CharField(max_length=512, verbose_name='证据摘要')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='证据载荷')),
                ('weight', models.CharField(choices=[('primary', '主证据'), ('supporting', '支撑证据'), ('context', '上下文')], default='supporting', max_length=16, verbose_name='权重')),
                ('collected_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='采集时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='aiops.aiopsincident', verbose_name='Incident')),
                ('source_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_evidence_items', to='aiops.aiopsexternaltask', verbose_name='来源任务')),
                ('tool_invocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_evidence_items', to='aiops.aiopstoolinvocation', verbose_name='工具调用')),
            ],
            options={
                'verbose_name': 'AIOps Incident 证据',
                'verbose_name_plural': 'AIOps Incident 证据',
                'ordering': ['-collected_at', '-id'],
                'indexes': [models.Index(fields=['incident', 'kind'], name='aiops_aiops_inciden_a88671_idx'), models.Index(fields=['source'], name='aiops_aiops_source_9dbca5_idx'), models.Index(fields=['collected_at'], name='aiops_aiops_collect_f331b6_idx')],
                'constraints': [models.UniqueConstraint(fields=('incident', 'kind', 'source'), name='aiops_incident_evidence_unique_source')],
            },
        ),
    ]
