# Generated by Django 6.0.6 on 2026-06-29 09:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiops', '0028_aiops_incident_evidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIOpsIncidentHypothesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='假设标题')),
                ('root_cause_type', models.CharField(choices=[('change_regression', '变更回归'), ('resource_saturation', '资源饱和'), ('dependency_failure', '依赖故障'), ('config_error', '配置错误'), ('capacity', '容量不足'), ('alert_symptom', '告警症状'), ('unknown', '未知')], default='unknown', max_length=32, verbose_name='根因类型')),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='置信度')),
                ('supporting_evidence_ids', models.JSONField(blank=True, default=list, verbose_name='支持证据 ID')),
                ('counter_evidence_ids', models.JSONField(blank=True, default=list, verbose_name='反证 ID')),
                ('missing_evidence', models.JSONField(blank=True, default=list, verbose_name='证据缺口')),
                ('recommended_next_checks', models.JSONField(blank=True, default=list, verbose_name='下一步检查')),
                ('summary', models.TextField(blank=True, default='', verbose_name='摘要')),
                ('status', models.CharField(choices=[('candidate', '候选'), ('primary', '主假设'), ('rejected', '已排除'), ('confirmed', '已确认')], default='candidate', max_length=16, verbose_name='状态')),
                ('generated_by', models.CharField(blank=True, default='rule_based', max_length=64, verbose_name='生成方式')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='生成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hypotheses', to='aiops.aiopsincident', verbose_name='Incident')),
                ('source_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_hypotheses', to='aiops.aiopsexternaltask', verbose_name='来源任务')),
            ],
            options={
                'verbose_name': 'AIOps Incident 根因假设',
                'verbose_name_plural': 'AIOps Incident 根因假设',
                'ordering': ['-confidence', '-generated_at', '-id'],
                'indexes': [models.Index(fields=['incident', 'status'], name='aiops_aiops_inciden_170ea5_idx'), models.Index(fields=['root_cause_type'], name='aiops_aiops_root_ca_5d7e2a_idx'), models.Index(fields=['generated_at'], name='aiops_aiops_generat_0508db_idx')],
            },
        ),
    ]
