# Generated by Django 6.0.6 on 2026-06-29 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiops', '0029_aiops_incident_hypothesis'),
        ('ops', '0057_delete_system_posture_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIOpsIncidentAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='动作标题')),
                ('action_type', models.CharField(choices=[('investigate', '继续调查'), ('mitigate', '缓解'), ('fix', '修复'), ('rollback', '回滚'), ('verify', '验证')], default='investigate', max_length=24, verbose_name='动作类型')),
                ('risk_level', models.CharField(choices=[('read_only', '只读'), ('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '极高')], default='read_only', max_length=16, verbose_name='风险等级')),
                ('status', models.CharField(choices=[('proposed', '待确认'), ('approved', '已批准'), ('running', '执行中'), ('completed', '已完成'), ('failed', '失败'), ('canceled', '已取消')], default='proposed', max_length=16, verbose_name='状态')),
                ('action_payload', models.JSONField(blank=True, default=dict, verbose_name='动作参数')),
                ('preconditions', models.JSONField(blank=True, default=list, verbose_name='前置条件')),
                ('rollback_plan', models.JSONField(blank=True, default=list, verbose_name='回滚计划')),
                ('verification_plan', models.JSONField(blank=True, default=list, verbose_name='验证计划')),
                ('verification_status', models.CharField(blank=True, default='', max_length=32, verbose_name='验证状态')),
                ('result_summary', models.TextField(blank=True, default='', verbose_name='执行结果摘要')),
                ('created_by', models.CharField(blank=True, default='system', max_length=64, verbose_name='创建人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('host_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aiops_incident_actions', to='ops.hosttask', verbose_name='任务中心任务')),
                ('hypothesis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_actions', to='aiops.aiopsincidenthypothesis', verbose_name='根因假设')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_actions', to='aiops.aiopsincident', verbose_name='Incident')),
                ('pending_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_actions', to='aiops.aiopspendingaction', verbose_name='待确认动作')),
            ],
            options={
                'verbose_name': 'AIOps Incident 处置建议',
                'verbose_name_plural': 'AIOps Incident 处置建议',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['incident', 'status'], name='aiops_aiops_inciden_b417cf_idx'), models.Index(fields=['action_type', 'risk_level'], name='aiops_aiops_action__b24f37_idx'), models.Index(fields=['pending_action'], name='aiops_aiops_pending_3ddf15_idx'), models.Index(fields=['host_task'], name='aiops_aiops_host_ta_0fe639_idx')],
            },
        ),
    ]
